### ISSUE TITLE
CentOS EoL

### ISSUE THREAD

**Issue by DangoNetwork** [unicorns/nvidia-license-server#4]
Hi dev,

CentOS is EOL now. All the repos are no longer valid. Could you please update it with Debian or Alpine? 

Thank you.

**Comment by ben-z** [comment]
NVIDIA actually [deprecated the licensing server](https://docs.nvidia.com/vgpu/news/vgpu-software-license-server-eol-notice/index.html) that this repo contains in favour of [NVIDIA License System (NLS)](https://docs.nvidia.com/license-system/latest/nvidia-license-system-user-guide/index.html#introduction-to-nvidia-license-system).

The NLS has options for cloud and on-prem deployment options: https://docs.nvidia.com/license-system/latest/nvidia-license-system-user-guide/index.html#about-service-instances and the on-prem deployment option natively supports containerized environments: https://docs.nvidia.com/license-system/latest/nvidia-license-system-user-guide/index.html#deploying-containerized-dls-software-image

I'll update the README and archive this repo.
